name = "Hermaphrodite RPG"
author = "Hermaphrodite-world"
version = "0.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6561b87d379ea477c740dc7b3ed5ebf186b7bfd38df7ed061d52b14f4dcd63a8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"
