name = "Hermaphrodite World"
author = "Hermaphrodite-world"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "15bb9cce1bc775b5378c81f52d1f3f8de2d324a5c1d96efbe193b64fa37d3c93"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
