name = "Hermaphrodite World"
author = "Hermaphrodite-world"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9929c5924565f349d65b693040d2d050daebfe78eb4066a91c55b03a9410f890"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
