name = "Hermaphrodite World"
author = "Hermaphrodite-world"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7da6c3717b3286d179479ebde67ba879a5c3f4933080034ae4437021744a9a09"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
